AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  CounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: kill-counter
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 3
      Events:
        GetCount:
          Type: Api
          Properties:
            Path: /kill-counter
            Method: GET
        IncrementCount:
          Type: Api
          Properties:
            Path: /kill-counter/increment
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CounterTable
